//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Diagramma_variantov
{
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// NewClass1.
    /// </summary>
    // *** Start programmer edit section *** (NewClass1 CustomAttributes)

    // *** End programmer edit section *** (NewClass1 CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class NewClass1 : ICSSoft.STORMNET.DataObject
    {

        private string fФИО;

        // *** Start programmer edit section *** (NewClass1 CustomMembers)

        // *** End programmer edit section *** (NewClass1 CustomMembers)


        /// <summary>
        /// ФИО.
        /// </summary>
        // *** Start programmer edit section *** (NewClass1.ФИО CustomAttributes)

        // *** End programmer edit section *** (NewClass1.ФИО CustomAttributes)
        [StrLen(255)]
        public virtual string ФИО
        {
            get
            {
                // *** Start programmer edit section *** (NewClass1.ФИО Get start)

                // *** End programmer edit section *** (NewClass1.ФИО Get start)
                string result = this.fФИО;
                // *** Start programmer edit section *** (NewClass1.ФИО Get end)

                // *** End programmer edit section *** (NewClass1.ФИО Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (NewClass1.ФИО Set start)

                // *** End programmer edit section *** (NewClass1.ФИО Set start)
                this.fФИО = value;
                // *** Start programmer edit section *** (NewClass1.ФИО Set end)

                // *** End programmer edit section *** (NewClass1.ФИО Set end)
            }
        }
    }
}

